services:
  - type: web
    name: peatio-crypto-exchange
    env: ruby
    runtime: ruby-2.7.8
    buildCommand: bundle install && bundle exec rake assets:precompile
    startCommand: bundle exec rails server -p $PORT -e $RAILS_ENV
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAKE_ENV
        value: production